version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            sudo apt update && sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3
      - run:
          name: Set up Repo And Sync
          command: |
            mkdir -p ~/android/rom && cd ~/android/rom
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            sudo ln -sf ~/bin/repo /usr/bin/repo
            git config --global user.name "kelexine"
            git config --global user.email "frankiekelechi@gmail.com"
            python3 ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
            python3 ~/bin/repo sync
      - run:
          name: Clone device tree
          command: |
            cd ~/android/rom
            git clone https://github.com/kelexine/android_device_tecno_KG5j -b android-11 device/tecno/KG5j
            git clone https://github.com/kelexine/android_vendor_tecno_KG5j -b KG5j vendor/tecno/KG5j
      - run:
          name: Build ROM
          command: |
            cd ~/android/rom
            source build/envsetup.sh
            lunch lineage_KG5j-eng
            mka bootimage
      - run:
          name: Upload artifact
          command: |
            cd ~/android/twrp
            circleci artifacts upload --path out/target/product/KG5j/*.img
            circleci artifacts upload --path out/target/product/KG5j/*.zip

workflows:
  main:
    jobs:
      - build
      
