
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick git lunzip lzop schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python-is-python3 perl xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 openjdk-11-jdk-headless -y
            export USER="kelexine"
      - run:
          name: Set up Repo
          command: |
            mkdir evo; cd evo
            git clone https://github.com/kelexine/EvolutionX_GSI.git -b evo
            
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            sudo ln -sf ~/bin/repo /usr/bin/repo
            git config --global user.name "kelexine"
            git config --global user.email "frankiekelechi@gmail.com
      - run:
          name: Setup CCACHE
          command: |
            cd evo
            mkdir ~/ccache
            export CCACHE_DIR=~/ccache
            export USE_CCACHE=1
            export CCACHE_EXEC=/usr/bin/ccache
            ccache -M 30G
            df -H
      - run:
          name: Start ROM Build
          command: |
            cd evo
            bash EvolutionX_GSI/build-a64.sh

workflows:
  main:
    jobs:
      - build

      
