
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            sudo apt update && sudo apt install -y bc bison build-essential ccache git-lfs curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3
      - run:
          name: Set up Repo And Sync LinageOS source
          command: |
            mkdir -p ~/android/lineage
            cd ~/android/lineage
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            sudo ln -sf ~/bin/repo /usr/bin/repo
            git config --global user.name "kelexine"
            git config --global user.email "frankiekelechi@gmail.com"
            python3 ~/bin/repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-19.1
            python3 ~/bin/repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j8
      - run:
          name: Clone Device Tree and Vendor Tree
          command: |
            cd ~/android/lineage
            git clone https://github.com/kelexine/android_device_tecno_KG5j -b android-11 device/tecno/KG5j
            git clone https://github.com/kelexine/android_vendor_tecno_KG5j -b KG5j vendor/tecno/KG5j
      - run:
          name: Setup CCACHE
          command: |
            cd ~/android/lineage
            mkdir ~/ccache
            export CCACHE_DIR=~/ccache
            export USE_CCACHE=1
            export CCACHE_EXEC=/usr/bin/ccache
            ccache -M 30G
            df -H
      - run:
          name: Start ROM Build
          command: |
            cd ~/android/lineage
            source build/envsetup.sh
            lunch lineage_KG5j-eng
            mka clean
            mka bacon -j10
            cd ~/android/lineage
            ls out
            ls out/target
            ls out/target/product
            ls out/target/product/KG5j
      - store_artifacts:
            path: |
               ~/android/lineage/out/target/product/KG5j/*.zip
               ~/android/lineage/out/target/product/KG5j/*.img
workflows:
  main:
    jobs:
      - build

      
